kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.satellite.k8sSupport.clusterRole }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/apisix/prometheus/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.satellite.k8sSupport.clusterRoleBinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.satellite.k8sSupport.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.satellite.k8sSupport.serviceAccount }}
    namespace: {{ .Release.Namespace }}
