apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "api7.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api7.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "api7.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    {{- end }}
      labels:
        {{- include "api7.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              hostPort: {{ .Values.gateway.http.port }}
              containerPort: {{ .Values.gateway.http.port }}
              protocol: TCP
            {{ if .Values.gateway.tls.enabled }}
            - name: tls
              hostPort: {{ .Values.gateway.tls.port }}
              containerPort: {{ .Values.gateway.tls.port }}
              protocol: TCP
            {{ end }}
            {{ if (and (has "prometheus" .Values.plugins) (get .Values.plugin_attr.prometheus "enable_export_server" )) }}
            - name: metric
              hostPort: {{ .Values.plugin_attr.prometheus.export_addr.port }}
              containerPort: {{ .Values.plugin_attr.prometheus.export_addr.port }}
              protocol: TCP
            {{ end }}
            {{- if .Values.gateway.stream_proxy }}
            {{- range .Values.gateway.stream_proxy.tcp }}
            - name: streamproxy{{ .addr }}
              hostPort: {{ .addr }}
              containerPort: {{ .addr }}
              protocol: TCP
            {{- end }}
            {{- range .Values.gateway.stream_proxy.udp }}
            - name: streamproxy{{ . }}
              hostPort: {{ . }}
              containerPort: {{ . }}
              protocol: UDP
            {{- end }}
            {{- end }}
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.gateway.http.port }}
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - "sleep 30"
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: apisix-config
              subPath: config.yaml
            {{- if .Values.etcd.auth.tls.enabled }}
            - mountPath: /etcd-ssl
              name: etcd-ssl
            {{- end }}
            {{- if and .Values.gateway.tls.enabled .Values.gateway.tls.existingCASecret }}
            - mountPath: /usr/local/apisix/conf/ssl
              name: ssl
            {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.etcd.builtin }}
      initContainers:
      - name: wait-etcd
        image: "{{ .Values.busybox.image.registry }}/{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
        command: ['sh', '-c', "until nc -zw 1 {{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} {{ .Values.etcd.defaultPort }}; do echo waiting for etcd `date`; sleep 2; done;"]
      {{- end }}
      volumes:
        - configMap:
            name: {{ include "api7.fullname" . }}
          name: apisix-config
        {{- if .Values.etcd.auth.tls.enabled }}
        - secret:
            secretName: {{ .Values.etcd.auth.tls.existingSecret | quote }}
          name: etcd-ssl
        {{- end }}
        {{- if and .Values.gateway.tls.enabled .Values.gateway.tls.existingCASecret }}
        - secret:
            secretName: {{ .Values.gateway.tls.existingCASecret | quote }}
          name: ssl
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity.enable }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "api7.name" . }}
              topologyKey: kubernetes.io/hostname
            weight: 100'
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

